### ISSUE TITLE
amplicon sequence reconstruction with swarm?

### ISSUE THREAD

**Issue by KabitaBaral1** [torognes/swarm#147]
Hello,

I am currently working on a genotyping project that involves the use of highly variable gene markers. We used the Nextera kit for the library preparation prior to illumina sequencing in paired-end mode (2x250 bp). I was wondering if Swarm performs a sequence reconstruction of my amplicons from my sheared reads (my marker size is about 850 bp). We are planning to label each cluster as one genotype across pooled samples (each sample is prone to have multiple genotypes). I was reading the study you published of Swarm, but I wasn't able to find anything related to sequence reconstruction from random breaks introduce by Nextera or a similar fragmentation approach. Is there any way I could use Swarm to solve this issue?

Thanks in advance,

Kabita Baral

**Comment by frederic-mahe** [comment]
Hi Kabita, if I understand correctly you have amplified long fragments (800-900 bp) of a marker, and these long fragments were randomly sheared pre-sequencing. You ended up with 2x250 bp read pairs, covering random parts of the long fragments, and you would like to reconstruct the fragments _in silico_.

I must say I have never had to deal with such data. I don't think swarm would be suited for that task. Maybe you could use vsearch's `search_global` function to select largely overlapping reads (without mismatches) to reconstruct full-length markers. Then you could map the raw-reads to these full-length markers to get abundance counts. But again, I am not sure I have a clear understanding of the data.

**Comment by colinbrislawn** [comment]
Hello Kabita,

I think Frédéric summarized this well. Because no single read covers the full region, your task is closer to genomic assembly. You might try a tool like [spades](http://cab.spbu.ru/software/spades/) for this task.

Panel A of [this figure](https://genome.cshlp.org/content/19/2/336/F2.expansion.html) illustrates one of the problems you will face.

![de Bruijn graph examples](https://genome.cshlp.org/content/19/2/336/F2.large.jpg)
As you can see, this sequence starts and ends the same, but there are multiple ways it can be combined in the middle. If I were doing this, I wouldn't want just one for these sequences. I would want _every possible read_ that could be seen here (every walk through the graph). And assembly tools will let you get that.

Once you have reconstructed your amplicon, [vsearch](https://github.com/torognes/vsearch/) is a great tool for mapping reads against it.

**Comment by KabitaBaral1** [comment]
Hey Torognes/Swarm,

Thank you very much for your help. I appreciate it.

Sincerely,
Kabita Baral
MS Bioinformatics
The University of Texas at El Paso

**Comment by frederic-mahe** [comment]
Thanks Colin for your input.
