### ISSUE TITLE
continuous integration service

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#158]
It seems that Travis CI is going to phase-out its free tier for open-source projects by the end of 2020:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

We might have to move to [GitHub Actions](https://github.com/features/actions).

**Comment by lczech** [comment]
That is so annoying. I'm thinking of contacting them to get some special deals for education and research projects (similar to what GitHub does). 

It is kind of understandable that they cannot offer their service for free for everyone, but with their current plans and [my current setup](https://travis-ci.org/github/lczech/genesis) (testing every OS they offer in combination with several compiler versions - because each of them tends to find different issues in C++), I would burn the whole free credit with just one build of my library... I guess for swarm, the travis setup is a whole lot simpler, so GitHub actions might work well here - but still, if any of you know of a Travis alternative that supports all kinds of OS's, please let me know!

**Comment by frederic-mahe** [comment]
Continuous integration seems to work for now. I am going to close that issue. We can revisit later if need be.
