### ISSUE TITLE
Assigning taxonomy to swarm centroids 

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/swarm#45]
Hello Frédéric,

Do you have a standard operating procedure for assigning taxonomy to a given swarm?

I'm accustomed to using [pre-clustered taxonomy databases](http://greengenes.secondgenome.com/downloads/database/13_5), but that would negate swarm's increated resolution of similar taxa. 

Thank you for your advice,
Colin

**Comment by frederic-mahe** [comment]
Hi Colin,

I have my own procedure. In a nutshell, take a reference database, truncate your reference sequences to keep only the in-between primers region; for each environmental amplicon, do a pairwise global alignment against that prepared reference database, to identify the closest reference(s).

In general, a swarm receives the same assignment than its most abundant amplicon (aka "the peak"). There are a few cases where a swarm might be assigned to a species-complex rather than to a single species (when the marker's resolution is not good enough).

I use a series of script to do that. They are tailor-made to accommodate the configuration of the cluster of computers I use, and are not really portable to other systems. I'd rather not distribute them, because I don't want to maintain them. We are working on a more general solution based on vsearch.

**Comment by colinbrislawn** [comment]
Hello Frederic,

Thanks for explaining your process to me. That seems very reasonable. I understand the desire not to distribute or support for personal workflow scripts.

I look forward to your vsearch solution. As I'm sure you know, [something similar](http://qiime.org/scripts/parallel_assign_taxonomy_uclust.html) has been done before, and is being [done again](http://drive5.com/usearch/manual/utax_algo.html).

Thank you,
Colin

**Comment by frederic-mahe** [comment]
Hi Colin,

you are right to indicate that similar solutions already exist. For me, the incentive to develop "yet another assignment method" is my taste for exact methods (as opposite to heuristics). I like the idea of using the most precise method we have to compare sequences, which is global pairwise alignment. Thanks to Torbjørn's work, the exact approach is (or soon will be) fast enough for today's largest datasets.

**Comment by colinbrislawn** [comment]
Hi Frederic,

Oh, I didn't mean to discourage this because it is similar approach to Edgar's methods. If anything, this is encouraging because 1) you know it works 2) you know you can improve on it 3) you know people want to use it. These people include me.

I'm excited by the development of vsearch because it directly addresses the two failing of usearch: closed source code and hard-to-verify heuristics.

Thanks!
Colin

**Comment by frederic-mahe** [comment]
Thanks Colin. I am going to close that issue then.
