### ISSUE TITLE
Complete integration of the fastidious option?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/swarm#55]
As of now, the results of the fastidious option are reported to the following output files: `--log` (`-l`), `--output-file` (`-o`), and `--seeds` (`-w`). The output file `--statistics-file` (`-s`) is partially updated (columns 6 and 7 are not updated). The output files `--internal-structure` (`-i`), `--mothur` (`-r`), and `--uclust-file` (`-u`) are not updated.

Updating the file `--statistics-file` seems difficult: the 6th and 7th columns report the number of growth iterations and the length of the longest, continuous, down-hill abundance path in the OTU. Updating these columns would break that idea of continuity.

Updating the other files would require to store intermediate results in memory and might prove difficult too.

**Comment by torognes** [comment]
The intermediate results are already stored in memory now (for version 2.1 and later). I think the output files in mothur format (-r) are already updated. The uclust files (-u) too. It is only the internal-structure (-i) file and columns 6 and 7 of the statistics file (-s) that are not updated. If not there must a bug.

**Comment by frederic-mahe** [comment]
You are right, I made a test: the `--mothur` (`-r`) and `--uclust-file` (`-u`) are updated.

So the output of the `--internal-structure` (`-i`) is the only thing that would make sense updating. Ideally, the grafted amplicons should receive a number of differences of 2. The fifth column of the structure file should be equal to `number of steps from seed to amplicon A + 2`. It would also require a significant reordering of the list of OTUs, as some OTUs will disappear. I mark that issue as a possible enhancement.

**Comment by torognes** [comment]
The cluster numbers in the uclust file and internal structure file were incorrect when the fastidious option was used, as there were gaps in the numbering corresponding to the light swarms that were grafted on the heavy swarms. This has now been corrected so that the cluster numbers are contiguous.

The structure file has been updated to include lines corresponding to the grafting links between amplicons in fastidious mode. They receive a value of 2 in the third column (differences) and the cluster number in the fourth column. In the 5th column they now get 1 + the generation of the linking amplicon in the heavy swarm, as if the grafting is considered one step. Maybe it should be 1 higher and be considered two steps?

For links within the light swarms the correct cluster is now indicated in column 4. The contents of the 5th column for the light swarms is more problematic. I have choosen to just keep this value as it is for these amplicons.

The problem with the fifth column for the light swarms is that the point of grafting in the light swarm may not be the original seed of that swarm. This could potentially require a complete reordering of the links and generations within the entire light swarm, including potential uphill (increasing abundance) walks. This seems counter-productive and I have choosen to keep them as they are.

**Comment by colinbrislawn** [comment]
>The structure file has been updated to include lines corresponding to the grafting links between amplicons in fastidious mode.

👏 💯 

---

>Maybe it should be 1 higher and be considered two steps?

I like counting it as **two** steps because when d=1, the links found by fastidious have an edit distance of two. I'm not sure what makes the most sense at d > 1.

**Comment by frederic-mahe** [comment]
> The cluster numbers in the uclust file and internal structure file were incorrect when the fastidious option was used, as there were gaps in the numbering corresponding to the light swarms that were grafted on the heavy swarms. This has now been corrected so that the cluster numbers are contiguous.

This is now covered by tests (see [this commit](https://github.com/frederic-mahe/swarm-tests/commit/d75bb059778fbae40a8ceb152c6eeb45864181dc))

**Comment by frederic-mahe** [comment]
> The problem with the fifth column for the light swarms is that the point of grafting in the light swarm may not be the original seed of that swarm. This could potentially require a complete reordering of the links and generations within the entire light swarm, including potential uphill (increasing abundance) walks. This seems counter-productive and I have choosen to keep them as they are.

I agree with that decision and I've created a test to confirm that behavior. That 5th column is problematic anyway, as it often overestimates the edition distance between amplicon and seed, especially for large OTUs.

I think I should rewrite the documentation to reflect that the information in the 5th column is merely indicative and should not be relied on for grafted amplicons.

**Comment by frederic-mahe** [comment]
documentation has been updated. I think that issue can be closed now.
