### ISSUE TITLE
Amplicon length truncation

### ISSUE THREAD

**Issue by vmikk** [torognes/swarm#66]
Hello!
Is it necessary to truncate amplicons to the common length to delineate OTUs with SWARM?
If so, how do you find a compromise between the truncation length and the number of remaining reads?

**Comment by colinbrislawn** [comment]
May I ask what sequencing technology was used to generate these reads? Because different sequencing technologies have different error profiles, the trade off between length and quality is different.

**Comment by vmikk** [comment]
**@colinbrislawn** Reads were generated with Illumina MiSeq. After trimming of adaptors and primers, and quality filtration their length distribution is relatively wide: from 100 (single end reads) to 500 bp (for the assembled paired ends).

**Comment by colinbrislawn** [comment]
What region did you amplify and how many base pairs are in it?
It sounds like you use a paired end MiSeq kit... is this a 250, 500, or 600 cycle kit?  

The reason I ask it that combination of region I sequence and kit that I use produce enough overlap to pair the forward and reverse read. This increases quality in the area of overlap, and produces reads of highly consistent length yielding truncating unnecessary.

**Comment by vmikk** [comment]
I’m sorry, I should be more specific. We sequenced amplicons of SSU rRNA of micro-eukaryotes with MiSeq (2x300). Expected amplicon length is 550 bp. Unfortunately, only 7% of sequences can be assembled from the paired-end reads (median length – 385, upper quartile – 450). For the rest of the data there is not enough overlap.
However it is possible to analyse only a part of amplicon. So the question is - does it have sense to combine the assembled amplicons and forward reads to delineate OTUs? Or we should truncate them (say, to the maximum length of R1)?
Of if we will work only with forward reads (unpaired reads that cover only partial amplicons, their lengths vary due to quality trimming) – should we adjust them to the common length (say, remove reads smaller than 150, and truncate the remaining reads to the length of 150)?

**Comment by frederic-mahe** [comment]
Hi @vmikk,

swarm does not require reads to be of the same length. However, you will obtain better results if your reads are **homologous**, i.e. covering the same region contained between a forward and a reverse primer. That homologous region can vary in length from one taxonomic clade to another, swarm doesn't care.

Now, if your reads do not reach your reverse primer, you can choose to truncate your reads to an arbitrary length. That's not ideal, but you should still get good results from swarm. When truncating, swarm will overestimate the cost of insertion-deletion events. For example:
```
initial reads:
ACGTACGTA
ACGTAACGTA

truncate to:
ACGTACGTA
ACGTAACGT

alignment:
ACGTA-CGTA
|||||-|||-
ACGTAACGT-
```
You can see in the above example that the cost of the insertion in read 2 is double (one internal gap + one terminal gap). Fortunately, Illumina sequencing produces far less indels than substitutions. So that overestimation problem is minor.

And, no, we will not modify swarm to neglect terminal gaps like other softwares do. Neglecting terminal gaps is similar in spirit to prefix clustering, and it is in my opinion a mistake in most situations (see [my rant on prefix clustering](https://github.com/torognes/swarm/wiki/advantages-of-swarm-over-prefix-clustering)).

**Comment by frederic-mahe** [comment]
> However it is possible to analyse only a part of amplicon. So the question is - does it have sense to combine the assembled amplicons and forward reads to delineate OTUs? Or we should truncate them (say, to the maximum length of R1)?
Or if we will work only with forward reads (unpaired reads that cover only partial amplicons, their lengths vary due to quality trimming) – should we adjust them to the common length (say, remove reads smaller than 150, and truncate the remaining reads to the length of 150)?

You should not delineate OTUs using a mix of assembled and unassembled reads.

Once, I had to work on a similar dataset. I truncated R1 and R2 to 200 bp, and joined them to build artificial reads. The objective was to keep most of the diversity signal contained in the dataset. I did the same to my reference sequences for taxonomic assignment. It worked, and the results will be used in an in prep. publication.

But again, it is utterly complicated, and primer pairs that can actually be joined by present sequencing techniques are to be preferred if possible.

**Comment by vmikk** [comment]
Hello **@frederic-mahe**,
Thank you for the comprehensive answer! It's clear for me, now.
And it is an interesting idea to build artificial R1-R2 reads. Maybe I'll give it a try.
