### ISSUE TITLE
Pacbio reads

### ISSUE THREAD

**Issue by davidvilanova** [torognes/swarm#81]
Is swarm suitable for long pacbio reads ?

thanks,

**Comment by frederic-mahe** [comment]
Hi @davidmartinad200, 

Because of pacbio's high-error rate and low-sequencing depth, swarm might not be the ideal tool. To confirm that, I would need to work on pacbio amplicon data (I never had the opportunity).

**Comment by davidmartinad200** [comment]
I´m working with 16S data. Error rate is being reduced by generated consensus sequences from Pacbio reads with at least 9 full passes and by having full length databases. Sequencing depth is not a problem because even if you get less reads they are longer and cover high regions where you would need much  more small reads to cover, so that´s not really a problem. (see paper https://peerj.com/articles/1869/ ).
My guess is that swarm should work pretty well (actually i have tried with a demo MOCK and was satisfied with the results).

**Comment by frederic-mahe** [comment]
Hi @davidmartinad200,

that sounds very interesting. The multi-pass approach to reduce overall error rates is great. My concern with sequencing depth is that swarm works better if you have a lot of sequences. "True" sequences and their clouds of micro-variants constitute a landscape where the altitude corresponds to the frequence (i.e. the copy number) of each sequence. To get copy-number, you need sequencing depth. However, I checked, pacbio seems to produce enough reads, so that should not be a problem for swarm.

Regarding parameters, I would suggest to try `-f -d 1` first. Starting from there, you can try `-d 2` or `-d 3` if you want to sacrifice some resolution to further reduce the number of singletons (although, there are better ways to do that, such as quality filtering and sample replicates). Swarm was designed to give results not-very-dependent from parameters, so there is not much to tweak with.

If you try swarm on long fragments, I'll be interested to get your feedback. I know swarm works well on amplicons ranging from 75 bp (old Illumina GAxII) to 400 bp (Illumina MiSeq v3). I'd be very happy to get a confirmation it also works on longer amplicons.

**Comment by davidmartinad200** [comment]
Yes, as i said we have tested with 16s data from a synthetic mock and swarm has performed well, we have recovered our expected species. Our amplicons were in between 1000 and 1600bp long.
david

**Comment by frederic-mahe** [comment]
I am going to close that issue. Feel free to open it again if you want to add to the conversation.

**Comment by zhangjl-work** [comment]
> 是的，正如我所说，我们已经用合成模拟的16S数据进行了测试，Swarm算法表现良好，我们成功扩增出了预期物种。扩增子长度在1000到1600bp之间。—— David

Could you tell me what parameters you use when processing PB Hi-Fi data? What is the appropriate setting for “d”?

**Comment by frederic-mahe** [comment]
I would start with the default `d` parameter with the fastidious option (`-d 1 -f`). Maybe @nhenry50 has some feedback on using swarm with PacBio Hi-Fi data?

**Comment by nhenry50** [comment]
I think `-d 1 -f` is indeed a good way to start, especially if you want to cluster sequencing errors. To cluster intra specific variability it will depends the marker you're using.

**Comment by zhangjl-work** [comment]
> 我认为`-d 1 -f`这确实是一个很好的切入点，尤其是在你想对测序错误进行聚类分析的情况下。至于如何对种内变异进行聚类分析，则取决于你使用的标记。

My input is a file named “unique.fa” containing 58 million records. When using d=1, the clustering process completed in 10 hours; however, when using d=2, it has been running for a week now and shows only clustering 2% completion—it seems extremely slow. Is this normal? I am using 2 TB of memory and 80 CPUs.
